[versions]
agp = "8.3.0-alpha07"
kotlin = "1.9.10"

[libraries]
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }